apiVersion: v1
kind: Pod
metadata:
   name: django-pod
   labels:
      app: django-ws
spec:
   containers:
   - name: django-container
     image: colemk/webserver:2.0
     ports:
       - containerPort: 80