apiVersion: v1
kind: Service
metadata:
   name: django-svc
   # Comment this out if running without designated IPs
   annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
      # Need to have allocated ips need 2 of them for our 1 zone
      # Do not put a space after comma I learned the hard way
      service.beta.kubernetes.io/aws-load-balancer-eip-allocations: eipalloc-086e597ddd60f2857,eipalloc-00e2d2bbdb5f73f01



      
     

      #Current domain http://ec2-54-205-23-234.compute-1.amazonaws.com/

      #service.beta.kubernetes.io/aws-load-balancer-ip-address-type: ipv4
spec:
   selector:
      app: django-ws
   ports:
   - protocol: TCP
     port: 80
     targetPort: 80
   type: LoadBalancer
   #loadBalancerIP: 54.205.23.234