apiVersion: v1
kind: Pod
metadata:
  name: ml-pod
  labels:
    app: ml-ws
spec:
  containers:
  - name: ml-container
    image: colemk/ml:2.0
    imagePullPolicy: Always

    env:
      # Define environment variables to use AWS credentials
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: aws-secret   # Name of your Kubernetes secret
            key: AWS_ACCESS_KEY_ID
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: aws-secret  # Name of your Kubernetes secret
            key: AWS_SECRET_ACCESS_KEY