# Generated by Django 5.0.1 on 2024-01-22 04:52

from django.db import migrations, models
from typing import List

class Migration(migrations.Migration):

    initial = True
    #Might need changed later but need this for linter
    dependencies:List[str] = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
